### ISSUE TITLE
Typescript Typings (*.d.ts)?

### ISSUE THREAD

**Issue by awwong1** [GraphQLCollege/graphql-postgres-subscriptions#1]
Are there any plans to add a typescript definition file (`index.d.ts`) to this project?

**Comment by JulianMayorga** [comment]
Hi Alexander,

Thanks for your question!

Type definitions would be very useful indeed. Personally I don't use Typescript, so I'm not very knowledgeable in this topic. But I will do some research on the topic. Type definitions would be useful even for non Typescript users because of intellisense.

Feel free to open up a PR with some type definitions if you have the time 😀 

Cheers,
Julian.

**Comment by awwong1** [comment]
Hi Julian!

I was having issues getting this to work with the pg-ipc dependency (also needed a custom reviver for notify). I wrote another module https://github.com/udia-software/graphql-postgres-subscriptions for my own use, but feel free to take a look if you're interested in adding typescript definitions to your project.

**Comment by JulianMayorga** [comment]
Your module looks very nice @awwong1!

I'm really interested in the typescript definitions indeed, I'll take a look at them later.

Could you tell me a bit about the issues you were having with `pg-ipc`?

Thanks so much!

**Comment by JulianMayorga** [comment]
Thanks for the info Alexander. I'll take a look at your library and see if I can improve this one based on your feedback.
